//! ESP8266 linker implementation.
//!
//! Links ESP8266 object files into `firmware.elf`, converts to `firmware.bin`
//! using esptool (with objcopy fallback), and reports size.
//!
//! Key differences from AVR:
//! - SDK precompiled libraries from `tools/sdk/lib/`
//! - Linker script from the board JSON `ldscript` field, resolved in `tools/sdk/ld/`
//! - Firmware conversion via `esptool --chip esp8266 elf2image`

use std::path::{Path, PathBuf};

use fbuild_core::subprocess::run_command;
use fbuild_core::{BuildProfile, Result, SizeInfo};

use super::mcu_config::Esp8266McuConfig;
use crate::linker::{LinkExtraArgs, Linker, LinkerScripts};

/// ESP8266-specific linker using Xtensa LX106 GCC as the link driver.
pub struct Esp8266Linker {
    gcc_path: PathBuf,
    ar_path: PathBuf,
    objcopy_path: PathBuf,
    size_path: PathBuf,
    /// Path to `tools/sdk/lib/` inside the framework.
    sdk_lib_dir: PathBuf,
    /// Path to `tools/sdk/lib/NONOSDK305/` — NonOS SDK version-specific libraries.
    sdk_nonosdk_lib_dir: PathBuf,
    /// Path to `tools/sdk/ld/` — needed by `generate_linker_scripts()` for template lookup.
    sdk_ld_dir: PathBuf,
    /// Board linker script + search directories.
    linker_scripts: LinkerScripts,
    mcu_config: Esp8266McuConfig,
    profile: BuildProfile,
    flash_mode: String,
    flash_freq: String,
    max_flash: Option<u64>,
    max_ram: Option<u64>,
    verbose: bool,
}

impl Esp8266Linker {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        gcc_path: PathBuf,
        ar_path: PathBuf,
        objcopy_path: PathBuf,
        size_path: PathBuf,
        sdk_lib_dir: PathBuf,
        sdk_nonosdk_lib_dir: PathBuf,
        sdk_ld_dir: PathBuf,
        linker_scripts: LinkerScripts,
        mcu_config: Esp8266McuConfig,
        profile: BuildProfile,
        flash_mode: Option<String>,
        flash_freq: &str,
        max_flash: Option<u64>,
        max_ram: Option<u64>,
        verbose: bool,
    ) -> Self {
        let flash_mode =
            flash_mode.unwrap_or_else(|| mcu_config.esptool.default_flash_mode.clone());
        Self {
            gcc_path,
            ar_path,
            objcopy_path,
            size_path,
            sdk_lib_dir,
            sdk_nonosdk_lib_dir,
            sdk_ld_dir,
            linker_scripts,
            mcu_config,
            profile,
            flash_mode,
            flash_freq: flash_freq.to_string(),
            max_flash,
            max_ram,
            verbose,
        }
    }
}

impl Esp8266Linker {
    /// Preprocess `eagle.app.v6.common.ld.h` → `local.eagle.app.v6.common.ld`.
    ///
    /// The board linker script (e.g. `eagle.flash.4m1m.ld`) includes
    /// `local.eagle.app.v6.common.ld` via the linker's `INCLUDE` directive.
    /// This file doesn't ship pre-built — it must be generated by running
    /// the GCC preprocessor on the `.ld.h` template with the correct defines.
    fn generate_linker_scripts(&self, output_dir: &Path) -> Result<()> {
        let ld_template = self.sdk_ld_dir.join("eagle.app.v6.common.ld.h");
        if !ld_template.exists() {
            return Err(fbuild_core::FbuildError::BuildFailed(format!(
                "ESP8266 linker script template not found: {}",
                ld_template.display()
            )));
        }
        let output_ld = output_dir.join("local.eagle.app.v6.common.ld");

        let mut args: Vec<String> = vec![self.gcc_path.to_string_lossy().to_string()];
        args.extend(["-CC".to_string(), "-E".to_string(), "-P".to_string()]);

        // Pass all MCU defines (VTABLES_IN_FLASH, MMU_IRAM_SIZE, etc.)
        for entry in &self.mcu_config.defines {
            match entry {
                crate::esp32::mcu_config::DefineEntry::Simple(name) => {
                    args.push(format!("-D{name}"));
                }
                crate::esp32::mcu_config::DefineEntry::KeyValue(name, value) => {
                    args.push(format!("-D{name}={value}"));
                }
            }
        }
        // FP_IN_IROM: place float printf/scanf in flash (required by the .ld.h template)
        args.push("-DFP_IN_IROM".to_string());

        args.push(ld_template.to_string_lossy().to_string());
        args.extend(["-o".to_string(), output_ld.to_string_lossy().to_string()]);

        let args_ref: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
        let result = run_command(&args_ref, None, None, None)?;
        if !result.success() {
            return Err(fbuild_core::FbuildError::BuildFailed(format!(
                "ESP8266 linker script preprocessing failed:\n{}",
                result.stderr
            )));
        }
        tracing::info!("generated local.eagle.app.v6.common.ld");
        Ok(())
    }
}

impl Linker for Esp8266Linker {
    fn archive(&self, objects: &[PathBuf], output: &Path) -> Result<()> {
        crate::linker::LinkerBase::archive(&self.ar_path, objects, output, "xtensa-lx106-elf-ar")
    }

    fn link(
        &self,
        objects: &[PathBuf],
        archives: &[PathBuf],
        output_dir: &Path,
        extra: &LinkExtraArgs,
    ) -> Result<PathBuf> {
        std::fs::create_dir_all(output_dir)?;

        // Preprocess linker script template before linking
        self.generate_linker_scripts(output_dir)?;

        let elf_path = output_dir.join("firmware.elf");
        let mut positional_archives: Vec<PathBuf> = archives
            .iter()
            .filter(|path| {
                path.extension()
                    .and_then(|ext| ext.to_str())
                    .map(|ext| ext.eq_ignore_ascii_case("a"))
                    .unwrap_or(false)
            })
            .cloned()
            .collect();
        let loose_objects: Vec<PathBuf> = archives
            .iter()
            .filter(|path| {
                !path
                    .extension()
                    .and_then(|ext| ext.to_str())
                    .map(|ext| ext.eq_ignore_ascii_case("a"))
                    .unwrap_or(false)
            })
            .cloned()
            .collect();

        if !loose_objects.is_empty() {
            let bundled_archive = output_dir.join("libfbuild-core.a");
            self.archive(&loose_objects, &bundled_archive)?;
            positional_archives.insert(0, bundled_archive);
        }

        let mut args: Vec<String> = vec![self.gcc_path.to_string_lossy().to_string()];

        // Linker flags from config
        args.extend(self.mcu_config.linker_flags.iter().cloned());

        // Profile-specific link flags
        if let Some(profile) = self.mcu_config.profiles.get(self.profile.as_dir_name()) {
            args.extend(profile.link_flags.iter().cloned());
        }
        args.extend(extra.flags.iter().cloned());

        // Build output dir — contains generated local.eagle.app.v6.common.ld
        args.push(format!("-L{}", output_dir.to_string_lossy()));
        // Board linker script + SDK ld search directory
        args.extend(self.linker_scripts.to_args());

        // PlatformIO relies on GCC's built-in search path for libc/libstdc++;
        // only the framework SDK directories are added explicitly here.
        args.push(format!("-L{}", self.sdk_lib_dir.to_string_lossy()));
        args.push(format!("-L{}", self.sdk_nonosdk_lib_dir.to_string_lossy()));

        args.extend(["-o".to_string(), elf_path.to_string_lossy().to_string()]);

        // Always emit a linker map next to firmware.elf for debugging (#305).
        let map_path = output_dir.join("firmware.map");
        args.push(format!("-Wl,-Map={}", map_path.to_string_lossy()));

        // Sketch objects first
        for obj in objects {
            args.push(obj.to_string_lossy().to_string());
        }

        // PlatformIO links the core archive inside the linker group together with
        // the SDK libraries. Keeping it outside the group leaves later SDK/core
        // cross-references like `settimeofday` unresolved.
        args.push("-Wl,--start-group".to_string());
        for archive in &positional_archives {
            args.push(archive.to_string_lossy().to_string());
        }
        args.extend(self.mcu_config.linker_libs.iter().cloned());
        args.extend(extra.libs.iter().cloned());
        args.push("-Wl,--end-group".to_string());

        if self.verbose {
            eprintln!("link: {}", args.join(" "));
            tracing::info!("link: {}", args.join(" "));
        }

        let args_ref: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
        let result = run_command(&args_ref, None, None, None)?;

        if !result.success() {
            return Err(fbuild_core::FbuildError::BuildFailed(format!(
                "xtensa-lx106-elf-gcc link failed:\n{}",
                result.stderr
            )));
        }

        Ok(elf_path)
    }

    fn convert_firmware(&self, elf_path: &Path, output_dir: &Path) -> Result<PathBuf> {
        let bin_path = output_dir.join("firmware.bin");

        // Try esptool first
        let elf_str = elf_path.to_string_lossy();
        let bin_str = bin_path.to_string_lossy();
        let args = [
            "esptool",
            "--chip",
            &self.mcu_config.esptool.chip,
            "elf2image",
            "--flash-mode",
            &self.flash_mode,
            "--flash-freq",
            &self.flash_freq,
            "--flash-size",
            &self.mcu_config.esptool.default_flash_size,
            &elf_str,
            "-o",
            &bin_str,
        ];

        match run_command(&args, None, None, Some(std::time::Duration::from_secs(30))) {
            Ok(result) if result.success() => {
                // Verify the output file was actually created with content.
                // ESP8266 esptool may create segmented files (firmware.bin-0x00000.bin)
                // instead of a single firmware.bin, leaving it empty.
                let size = std::fs::metadata(&bin_path).map(|m| m.len()).unwrap_or(0);
                if size > 0 {
                    tracing::info!("converted ELF → firmware.bin via esptool");
                    return Ok(bin_path);
                }
                tracing::debug!("esptool produced empty firmware.bin (falling back to objcopy)");
            }
            Ok(result) => {
                tracing::debug!(
                    "esptool elf2image failed (falling back to objcopy): {}",
                    result.stderr
                );
            }
            Err(e) => {
                tracing::debug!("esptool not found (falling back to objcopy): {}", e);
            }
        }

        // Fallback to objcopy
        crate::linker::LinkerBase::objcopy_firmware(
            &self.objcopy_path,
            elf_path,
            output_dir,
            &self.mcu_config.objcopy.output_format,
            &self.mcu_config.objcopy.remove_sections,
            "xtensa-lx106-elf-objcopy",
        )
    }

    fn size_tool_path(&self) -> &Path {
        &self.size_path
    }

    fn report_size(&self, elf_path: &Path) -> Result<SizeInfo> {
        crate::linker::LinkerBase::report_size(
            &self.size_path,
            elf_path,
            self.max_flash,
            self.max_ram,
            "xtensa-lx106-elf-size",
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::esp8266::mcu_config::get_esp8266_config;

    #[test]
    fn test_esp8266_linker_creation() {
        let linker = Esp8266Linker::new(
            PathBuf::from("/bin/xtensa-lx106-elf-gcc"),
            PathBuf::from("/bin/xtensa-lx106-elf-ar"),
            PathBuf::from("/bin/xtensa-lx106-elf-objcopy"),
            PathBuf::from("/bin/xtensa-lx106-elf-size"),
            PathBuf::from("/sdk/lib"),
            PathBuf::from("/sdk/lib/NONOSDK305"),
            PathBuf::from("/sdk/ld"),
            LinkerScripts::single(PathBuf::from("/sdk/ld"), "eagle.flash.4m1m.ld"),
            get_esp8266_config().unwrap(),
            BuildProfile::Release,
            Some("dio".to_string()),
            "40m",
            Some(4_194_304),
            Some(81_920),
            false,
        );
        assert!(linker
            .linker_scripts
            .scripts
            .iter()
            .any(|s| s.contains("eagle.flash.4m1m")));
        assert_eq!(linker.max_flash, Some(4_194_304));
        assert_eq!(linker.max_ram, Some(81_920));
        assert_eq!(linker.flash_mode, "dio");
    }
}
