//! udev rule generation for Linux serial access (FastLED/fbuild#1424).
//!
//! On Linux, serial device nodes are `root:dialout 0660` and the invoking
//! user is usually not in `dialout`. `fbuild deploy` then flashes
//! successfully and cannot reopen the port it just flashed, which surfaces
//! as a post-deploy timeout rather than a permissions error.
//!
//! A one-shot `chmod` does not hold: the deploy cycle re-enumerates the board
//! (BOOTSEL -> application), and udev recreates the node with default
//! ownership before fbuild reopens it. Only a rule keyed on vendor ID
//! survives re-enumeration, which is why this generates rules rather than
//! touching device nodes.
//!
//! The vendor list comes from the ingested FastLED/boards registry, never a
//! local table -- see the USB VID/PID source-of-truth rule. A hand-written
//! copy would drift the moment a vendor is ingested.
//!
//! This module only *renders* text. Installing is deliberately left to the
//! caller: on NixOS `/etc` is generated from declarative config, so a written
//! file there is both out-of-band and liable to be clobbered. What those users
//! need is the content for `services.udev.extraRules`, not a mutation.

/// Group granted access by generated rules. `plugdev` is the conventional
/// choice for pluggable non-storage hardware and, unlike `dialout`, does not
/// also confer modem/PPP access.
pub const DEFAULT_UDEV_GROUP: &str = "plugdev";

/// Filename the rules are installed as. It must sort before logind's
/// `73-seat-late.rules`, which is what turns `TAG+="uaccess"` into an ACL;
/// the previous `99-` name was too late for that (FastLED/fbuild#1621).
pub const UDEV_RULES_FILENAME: &str = "70-fbuild.rules";

/// Name earlier fbuild versions told users to install as; the installer
/// removes it so two generations of rules do not coexist.
pub const LEGACY_UDEV_RULES_FILENAME: &str = "99-fbuild.rules";

/// Device-node subsystems each vendor gets a rule for: the serial port, the
/// raw USB device (probe-rs, picotool, DFU) and HID loaders.
pub const RULE_SUBSYSTEMS: [&str; 3] = ["tty", "usb", "hidraw"];

/// `group` if it exists in `group_file` (normally `/etc/group`), else None.
///
/// Distros differ: Debian/Ubuntu ship `plugdev`, while NixOS, Arch and Fedora
/// do not. A rule naming a missing group is discarded whole by udev, so the
/// default group is only used where it resolves (FastLED/fbuild#1621).
pub fn existing_group<'a>(group: &'a str, group_file: &str) -> Option<&'a str> {
    group_file
        .lines()
        .any(|l| l.split(':').next() == Some(group))
        .then_some(group)
}

/// [`DEFAULT_UDEV_GROUP`] when this host has it.
pub fn host_default_group() -> Option<&'static str> {
    let file = std::fs::read_to_string("/etc/group").unwrap_or_default();
    existing_group(DEFAULT_UDEV_GROUP, &file)
}

/// Whether `group` is a plausible Unix group name.
///
/// The rendered value lands inside a quoted udev field in a file an operator
/// installs as root, so a `"` or a newline here could close the quote and
/// append rules of the caller's choosing. udev only unescapes `\\"` inside a
/// standard quoted string, so there is no encoding that makes arbitrary input
/// safe -- reject it instead. Mirrors the useradd(8) NAME_REGEX: an initial
/// alphanumeric or underscore, then alphanumerics, underscore, hyphen or dot.
pub fn is_valid_group_name(group: &str) -> bool {
    if group.is_empty() || group.len() > 32 {
        return false;
    }
    let mut chars = group.chars();
    let first = chars.next().unwrap_or('\0');
    if !(first.is_ascii_alphanumeric() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-' || c == '.')
}

/// Render udev rules granting `group` access to every vendor in `vids`.
///
/// Returns `None` when `vids` is empty, or when `group` is not a valid group
/// name. Both are real cases -- the registry overlay may not be installed, and
/// `--group` is caller-supplied -- and emitting a header with no rules, or a
/// rule built from an unvalidated group, would hand back a file that looks
/// configured while granting nothing or granting the wrong thing.
pub fn render_udev_rules(vids: &[u16], group: Option<&str>) -> Option<String> {
    if vids.is_empty() || group.is_some_and(|g| !is_valid_group_name(g)) {
        return None;
    }
    let mut sorted: Vec<u16> = vids.to_vec();
    sorted.sort_unstable();
    sorted.dedup();

    let mut out = String::new();
    out.push_str("# Generated by `fbuild port udev`. Do not edit by hand.\n");
    out.push_str("#\n");
    out.push_str("# Grants access to the serial, raw USB and hidraw nodes of every USB\n");
    out.push_str("# vendor in the FastLED/boards registry: to the active local user via\n");
    out.push_str("# uaccess (no group or re-login needed), and to the listed group for\n");
    out.push_str("# SSH/headless sessions. Regenerate after upgrading fbuild to pick up\n");
    out.push_str("# newly ingested vendors (`fbuild port udev --install`).\n");
    out.push_str("#\n");
    out.push_str(&format!(
        "# Install as /etc/udev/rules.d/{UDEV_RULES_FILENAME}, then:\n"
    ));
    out.push_str("#   sudo udevadm control --reload-rules && sudo udevadm trigger\n");
    if let Some(group) = group {
        out.push_str(&format!(
            "# For SSH/headless sessions also add your user to '{group}' and re-login.\n"
        ));
    }
    out.push_str("#\n");
    out.push_str("# On NixOS, paste the rules below into services.udev.extraRules instead;\n");
    out.push_str("# /etc there is generated and a hand-written file will not persist.\n");
    out.push('\n');

    for vid in sorted {
        // Lowercase hex without an 0x prefix: udev compares ATTRS{idVendor}
        // as a string against sysfs, which renders it exactly this way. An
        // uppercase or 0x-prefixed value silently never matches.
        // GROUP only when it exists: udev drops the *whole line* for an
        // unknown group ("Failed to resolve group"), uaccess included.
        let group_field = group
            .map(|g| format!("GROUP=\"{g}\", "))
            .unwrap_or_default();
        for subsystem in RULE_SUBSYSTEMS {
            out.push_str(&format!(
                "SUBSYSTEM==\"{subsystem}\", ATTRS{{idVendor}}==\"{vid:04x}\", \
                 MODE=\"0660\", {group_field}TAG+=\"uaccess\"\n"
            ));
        }
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_registry_yields_no_rules() {
        // Not an empty file: a header with no rules would look configured
        // while granting nothing.
        assert!(render_udev_rules(&[], Some(DEFAULT_UDEV_GROUP)).is_none());
    }

    #[test]
    fn renders_lowercase_four_digit_hex() {
        // udev matches ATTRS{idVendor} as a string against sysfs. "0x2E8A"
        // or "2E8A" never match, and the failure is silent.
        let out = render_udev_rules(&[0x2e8a, 0x303a], Some(DEFAULT_UDEV_GROUP)).unwrap();
        assert!(out.contains(r#"ATTRS{idVendor}=="2e8a""#));
        assert!(out.contains(r#"ATTRS{idVendor}=="303a""#));
        assert!(!out.contains("0x2e8a"));
        assert!(!out.contains("2E8A"));
    }

    #[test]
    fn pads_short_vids_to_four_digits() {
        let out = render_udev_rules(&[0x403], Some(DEFAULT_UDEV_GROUP)).unwrap();
        assert!(out.contains(r#"ATTRS{idVendor}=="0403""#), "{out}");
    }

    #[test]
    fn sorts_and_dedups() {
        let out = render_udev_rules(&[0x303a, 0x2e8a, 0x303a], Some(DEFAULT_UDEV_GROUP)).unwrap();
        let rules: Vec<&str> = out
            .lines()
            .filter(|l| l.starts_with("SUBSYSTEM=="))
            .collect();
        assert_eq!(
            rules.len(),
            2 * RULE_SUBSYSTEMS.len(),
            "duplicate VID must collapse: {out}"
        );
        assert!(rules[0].contains("2e8a"), "not sorted: {out}");
        assert!(rules.last().unwrap().contains("303a"), "not sorted: {out}");
    }

    #[test]
    fn rejects_a_group_that_could_break_out_of_the_quoted_value() {
        // The rendered value sits inside a quoted udev field in a file an
        // operator installs as root; a quote or newline could append rules.
        for bad in [
            "plug\"dev",
            "plugdev\nSUBSYSTEM==\"tty\", MODE=\"0666\"",
            "",
            "-leading-hyphen",
            ".leading-dot",
            "has space",
            "semi;colon",
            "sl/ash",
        ] {
            assert!(
                render_udev_rules(&[0x2e8a], Some(bad)).is_none(),
                "must reject {bad:?}"
            );
        }
    }

    #[test]
    fn accepts_ordinary_group_names() {
        for good in ["plugdev", "dialout", "users", "_svc", "grp.1", "a-b_c.d"] {
            assert!(is_valid_group_name(good), "must accept {good:?}");
        }
    }

    #[test]
    fn rejects_an_overlong_group_name() {
        assert!(!is_valid_group_name(&"a".repeat(33)));
        assert!(is_valid_group_name(&"a".repeat(32)));
    }

    /// udev discards a whole rule line whose GROUP does not resolve, so a host
    /// without the group must get no GROUP field at all (uaccess still works).
    #[test]
    fn omits_group_when_the_host_lacks_it() {
        let out = render_udev_rules(&[0x1fc9], None).unwrap();
        assert!(!out.contains("GROUP="), "{out}");
        assert!(out.contains(r#"TAG+="uaccess""#), "{out}");
    }

    #[test]
    fn existing_group_reads_the_group_database() {
        let etc_group = "root:x:0:\nplugdev:x:46:alice\nusers:x:100:\n";
        assert_eq!(existing_group("plugdev", etc_group), Some("plugdev"));
        assert_eq!(existing_group("plugdev", "root:x:0:\nusers:x:100:\n"), None);
        // A member list mentioning the name is not the group itself.
        assert_eq!(existing_group("alice", etc_group), None);
    }

    #[test]
    fn honors_the_requested_group() {
        let out = render_udev_rules(&[0x2e8a], Some("wheel")).unwrap();
        assert!(out.contains(r#"GROUP="wheel""#));
        assert!(!out.contains(r#"GROUP="plugdev""#));
    }

    #[test]
    fn every_vid_gets_one_rule_per_subsystem() {
        let vids: Vec<u16> = vec![0x2e8a, 0x303a, 0x0403, 0x1a86, 0x10c4, 0x16c0];
        let out = render_udev_rules(&vids, Some(DEFAULT_UDEV_GROUP)).unwrap();
        let rules = out.lines().filter(|l| l.starts_with("SUBSYSTEM==")).count();
        assert_eq!(rules, vids.len() * RULE_SUBSYSTEMS.len(), "{out}");
    }

    /// FastLED/fbuild#1621: probe-rs, picotool and DFU open the raw USB node
    /// (and HID loaders the hidraw node), not the tty, so tty-only rules leave
    /// them failing with "could not open the USB device".
    #[test]
    fn covers_raw_usb_and_hidraw_not_just_tty() {
        let out = render_udev_rules(&[0x1fc9], Some(DEFAULT_UDEV_GROUP)).unwrap();
        for subsystem in ["tty", "usb", "hidraw"] {
            assert!(
                out.contains(&format!(
                    r#"SUBSYSTEM=="{subsystem}", ATTRS{{idVendor}}=="1fc9""#
                )),
                "missing {subsystem}: {out}"
            );
        }
    }

    /// `uaccess` grants the active local user an ACL with no group membership
    /// or re-login. logind applies it in 73-seat-late.rules, so the file must
    /// sort before 73 or the tag is never acted on.
    #[test]
    fn tags_uaccess_and_sorts_before_seat_late() {
        let out = render_udev_rules(&[0x1fc9], Some(DEFAULT_UDEV_GROUP)).unwrap();
        let rules: Vec<&str> = out
            .lines()
            .filter(|l| l.starts_with("SUBSYSTEM=="))
            .collect();
        assert!(
            rules.iter().all(|r| r.contains(r#"TAG+="uaccess""#)),
            "{out}"
        );
        let prio: u32 = UDEV_RULES_FILENAME[..2].parse().unwrap();
        assert!(
            prio < 73,
            "{UDEV_RULES_FILENAME} sorts after 73-seat-late.rules"
        );
    }
}
