//! udev rule generation for Linux serial access (FastLED/fbuild#1424).
//!
//! On Linux, serial device nodes are `root:dialout 0660` and the invoking
//! user is usually not in `dialout`. `fbuild deploy` then flashes
//! successfully and cannot reopen the port it just flashed, which surfaces
//! as a post-deploy timeout rather than a permissions error.
//!
//! A one-shot `chmod` does not hold: the deploy cycle re-enumerates the board
//! (BOOTSEL -> application), and udev recreates the node with default
//! ownership before fbuild reopens it. Only a rule keyed on vendor ID
//! survives re-enumeration, which is why this generates rules rather than
//! touching device nodes.
//!
//! The vendor list comes from the ingested FastLED/boards registry, never a
//! local table -- see the USB VID/PID source-of-truth rule. A hand-written
//! copy would drift the moment a vendor is ingested.
//!
//! This module only *renders* text. Installing is deliberately left to the
//! caller: on NixOS `/etc` is generated from declarative config, so a written
//! file there is both out-of-band and liable to be clobbered. What those users
//! need is the content for `services.udev.extraRules`, not a mutation.

/// Group granted access by generated rules. `plugdev` is the conventional
/// choice for pluggable non-storage hardware and, unlike `dialout`, does not
/// also confer modem/PPP access.
pub const DEFAULT_UDEV_GROUP: &str = "plugdev";

/// Filename callers should install as, if they install at all. The `99-`
/// prefix keeps it last so it overrides earlier distro rules.
pub const UDEV_RULES_FILENAME: &str = "99-fbuild.rules";

/// Render udev rules granting `group` access to every vendor in `vids`.
///
/// Returns `None` when `vids` is empty. That is a real case -- the registry
/// overlay may not be installed -- and emitting a header with no rules would
/// hand back a file that looks configured and grants nothing.
pub fn render_udev_rules(vids: &[u16], group: &str) -> Option<String> {
    if vids.is_empty() {
        return None;
    }
    let mut sorted: Vec<u16> = vids.to_vec();
    sorted.sort_unstable();
    sorted.dedup();

    let mut out = String::new();
    out.push_str("# Generated by `fbuild port udev`. Do not edit by hand.\n");
    out.push_str("#\n");
    out.push_str("# Grants the listed group access to serial ports for every USB vendor\n");
    out.push_str("# in the FastLED/boards registry, so `fbuild deploy` can reopen a port\n");
    out.push_str("# after the board re-enumerates. Regenerate after upgrading fbuild to\n");
    out.push_str("# pick up newly ingested vendors.\n");
    out.push_str("#\n");
    out.push_str(&format!("# Install as /etc/udev/rules.d/{UDEV_RULES_FILENAME}, then:\n"));
    out.push_str("#   sudo udevadm control --reload-rules && sudo udevadm trigger\n");
    out.push_str(&format!("# Ensure your user is in the '{group}' group, then log out and back in.\n"));
    out.push_str("#\n");
    out.push_str("# On NixOS, paste the rules below into services.udev.extraRules instead;\n");
    out.push_str("# /etc there is generated and a hand-written file will not persist.\n");
    out.push('\n');

    for vid in sorted {
        // Lowercase hex without an 0x prefix: udev compares ATTRS{idVendor}
        // as a string against sysfs, which renders it exactly this way. An
        // uppercase or 0x-prefixed value silently never matches.
        out.push_str(&format!(
            "SUBSYSTEM==\"tty\", ATTRS{{idVendor}}==\"{vid:04x}\", GROUP=\"{group}\", MODE=\"0660\"\n"
        ));
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_registry_yields_no_rules() {
        // Not an empty file: a header with no rules would look configured
        // while granting nothing.
        assert!(render_udev_rules(&[], DEFAULT_UDEV_GROUP).is_none());
    }

    #[test]
    fn renders_lowercase_four_digit_hex() {
        // udev matches ATTRS{idVendor} as a string against sysfs. "0x2E8A"
        // or "2E8A" never match, and the failure is silent.
        let out = render_udev_rules(&[0x2e8a, 0x303a], DEFAULT_UDEV_GROUP).unwrap();
        assert!(out.contains(r#"ATTRS{idVendor}=="2e8a""#));
        assert!(out.contains(r#"ATTRS{idVendor}=="303a""#));
        assert!(!out.contains("0x2e8a"));
        assert!(!out.contains("2E8A"));
    }

    #[test]
    fn pads_short_vids_to_four_digits() {
        let out = render_udev_rules(&[0x403], DEFAULT_UDEV_GROUP).unwrap();
        assert!(out.contains(r#"ATTRS{idVendor}=="0403""#), "{out}");
    }

    #[test]
    fn sorts_and_dedups() {
        let out = render_udev_rules(&[0x303a, 0x2e8a, 0x303a], DEFAULT_UDEV_GROUP).unwrap();
        let rules: Vec<&str> = out.lines().filter(|l| l.starts_with("SUBSYSTEM==")).collect();
        assert_eq!(rules.len(), 2, "duplicate VID must collapse: {out}");
        assert!(rules[0].contains("2e8a"), "not sorted: {out}");
        assert!(rules[1].contains("303a"), "not sorted: {out}");
    }

    #[test]
    fn honors_the_requested_group() {
        let out = render_udev_rules(&[0x2e8a], "wheel").unwrap();
        assert!(out.contains(r#"GROUP="wheel""#));
        assert!(!out.contains(r#"GROUP="plugdev""#));
    }

    #[test]
    fn every_vid_gets_exactly_one_rule() {
        let vids: Vec<u16> = vec![0x2e8a, 0x303a, 0x0403, 0x1a86, 0x10c4, 0x16c0];
        let out = render_udev_rules(&vids, DEFAULT_UDEV_GROUP).unwrap();
        let rules = out.lines().filter(|l| l.starts_with("SUBSYSTEM==")).count();
        assert_eq!(rules, vids.len(), "{out}");
    }
}
