name: Build SuperMini nRF52840

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "SuperMini nRF52840"
      test-dir: "tests/platform/supermini_nrf52840"
      env-name: "supermini_nrf52840"
      firmware-ext: "hex"
