name: Build Teensy 3.2

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "Teensy 3.2"
      test-dir: "tests/platform/teensy32"
      env-name: "teensy32"
      firmware-ext: "hex"
