name: Build ATmega8A

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "ATmega8A"
      test-dir: "tests/platform/atmega8a"
      env-name: "atmega8a"
      firmware-ext: "hex"
