name: Build BluePill F103C8

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "BluePill F103C8"
      test-dir: "tests/platform/bluepill_f103c8"
      env-name: "bluepill"
      firmware-ext: "hex"
