name: Build STM32H747XI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "STM32H747XI"
      test-dir: "tests/platform/stm32h747xi"
      env-name: "stm32h747xi"
      firmware-ext: "bin"
