name: Build LPCXpresso845-MAX

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "NXP LPCXpresso845-MAX"
      test-dir: "tests/platform/lpcxpresso845max"
      env-name: "lpcxpresso845max"
      firmware-ext: "bin"
