name: Build STM32F411CE

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "STM32F411CE"
      test-dir: "tests/platform/stm32f411ce"
      env-name: "stm32f411ce"
      firmware-ext: "hex"
