name: Build SAMD21

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "SAMD21"
      test-dir: "tests/platform/samd21"
      env-name: "samd21"
      firmware-ext: "bin"
