name: Build Apollo3 RedBoard

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "Apollo3 RedBoard"
      test-dir: "tests/platform/apollo3_red"
      env-name: "apollo3_red"
      firmware-ext: "bin"
