name: Build ESP32-C2

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "ESP32-C2"
      test-dir: "tests/platform/esp32c2"
      env-name: "esp32c2"
      firmware-ext: "bin"
