name: Build LPC845

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "NXP LPC845-BRK"
      test-dir: "tests/platform/lpc845"
      env-name: "lpc845"
      firmware-ext: "bin"
