name: Build Teensy 3.0

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "Teensy 3.0"
      test-dir: "tests/platform/teensy30"
      env-name: "teensy30"
      firmware-ext: "hex"
