name: Build LPCXpresso804

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/template_build.yml
    with:
      workflow-name: "NXP LPCXpresso804"
      test-dir: "tests/platform/lpcxpresso804"
      env-name: "lpcxpresso804"
      firmware-ext: "bin"
